development:
  adapter: mysql2
  database: polar_development
  encoding: utf8
  host: 127.0.0.1
  username: root
  password:

test:
  adapter: mysql2
  database: polar_test
  encoding: utf8
  host: 127.0.0.1
  username: root
  password:
